<%@ Page Title="" Language="C#" MasterPageFile="~/admin.master" AutoEventWireup="true" CodeFile="Manage_Students.aspx.cs" Inherits="admin_Manage_Students" %>

<%@ Register Assembly="Telerik.Web.UI" Namespace="Telerik.Web.UI" TagPrefix="telerik" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" Runat="Server">
<script type="text/javascript">
    function mngRequestStarted(ajaxManager, eventArgs) {
        if (eventArgs.EventTarget == "mngBtnExcel" || eventArgs.EventTarget == "mngBtnWord") {
            eventArgs.EnableAjax = false;
        }
    }
    function pnlRequestStarted(ajaxPanel, eventArgs) {
        if (eventArgs.EventTarget == "pnlBtnExcel" || eventArgs.EventTarget == "pnlBtnWord") {
            eventArgs.EnableAjax = false;
        }
    }
    function gridRequestStart(grid, eventArgs) {
        if ((eventArgs.EventTarget.indexOf("gridBtnExcel") != -1) || (eventArgs.EventTarget.indexOf("gridBtnWord") != -1)) {
            eventArgs.EnableAjax = false;
        }
    }
</script>
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="sidebartop_placeholder" Runat="Server">
</asp:Content>
<asp:Content ID="Content3" ContentPlaceHolderID="sidebarbottom_placeholder" Runat="Server">
</asp:Content>
<asp:Content ID="Content4" ContentPlaceHolderID="content_heading" Runat="Server">
Manage Students<asp:ScriptManager ID="ScriptManager1" runat="server">
    </asp:ScriptManager>
</asp:Content>
<asp:Content ID="Content5" ContentPlaceHolderID="content_placeholder" Runat="Server">
   

<table>
    <tr>
        <td>
         Year :
        </td>
        <td>
            <asp:DropDownList ID="DropDownList1" runat="server" AutoPostBack="True" 
                DataSourceID="LinqDataSource1" DataTextField="Year1" DataValueField="Year1">
            </asp:DropDownList>
            <asp:LinqDataSource ID="LinqDataSource1" runat="server" 
                ContextTypeName="Datbase_ClassesDataContext" EntityTypeName="" 
                TableName="Years">
            </asp:LinqDataSource>
        </td>
        <td>
            Course :
        </td>
        <td>
            <asp:DropDownList ID="DropDownList2" runat="server" AutoPostBack="True" 
                DataSourceID="LinqDataSource2" DataTextField="Course1" DataValueField="ID">
            </asp:DropDownList>
            <asp:LinqDataSource ID="LinqDataSource2" runat="server" 
                ContextTypeName="Datbase_ClassesDataContext" EntityTypeName="" 
                TableName="Courses">
            </asp:LinqDataSource>
        </td>
        <td>
            Department :
        </td>
        <td>
            <asp:DropDownList ID="DropDownList3" runat="server" AutoPostBack="True" 
                DataSourceID="LinqDataSource4" DataTextField="Department1" DataValueField="ID">
            </asp:DropDownList>
            <asp:LinqDataSource ID="LinqDataSource4" runat="server" 
                ContextTypeName="Datbase_ClassesDataContext" EntityTypeName="" 
                TableName="Departments">
            </asp:LinqDataSource>
        </td>
    </tr>
</table>
<br />
<div style="padding:10px 20px 10px 10px;">
        <telerik:RadGrid ID="RadGrid1" runat="server" AllowPaging="True" 
            AllowSorting="True" DataSourceID="LinqDataSource3" GridLines="None" 
            ShowGroupPanel="True" Skin="Windows7" onitemcommand="RadGrid1_ItemCommand" 
            AllowMultiRowSelection="True" AutoGenerateDeleteColumn="True" 
            ondeletecommand="RadGrid1_DeleteCommand">
            <ExportSettings ExportOnlyData="True" FileName="Exported_Sid" 
                OpenInNewWindow="True">
<Pdf PaperSize="Letter" AllowAdd="True" Author="Siddhartha" Creator="T and P" 
                    Title="Exported from TandP portal" />
</ExportSettings>
            <ClientSettings AllowDragToGroup="True">
                <Selecting AllowRowSelect="True" />
                <Scrolling AllowScroll="True" UseStaticHeaders="True" />
            </ClientSettings>
           

            <MasterTableView autogeneratecolumns="False" datakeynames="Student_ID" 
                datasourceid="LinqDataSource3" CommandItemDisplay="Top">
                <CommandItemSettings ExportToPdfText="Export to Pdf" 
                    ShowAddNewRecordButton="False" ShowExportToCsvButton="True" 
                    ShowExportToExcelButton="True" ShowExportToWordButton="True" />
                <RowIndicatorColumn>
                    <HeaderStyle Width="20px" />
                </RowIndicatorColumn>
                <ExpandCollapseColumn>
                    <HeaderStyle Width="20px" />
                </ExpandCollapseColumn>
                 <CommandItemTemplate>
            <div style="padding: 5px 5px;">
          
                       
<asp:LinkButton ID="LinkButton1" OnClientClick="javascript:return confirm('Do you want to delete all selected items?')"
runat="server" CommandName="DeleteSelected"><img style="border:0px;vertical-align:middle;" alt="" src="../assets/images/Icons/Delete.gif" />Delete selected!</asp:LinkButton>&nbsp;&nbsp;
                        <asp:LinkButton ID="LinkButton4" runat="server" CommandName="RebindGrid"><img style="border:0px;vertical-align:middle;" alt="" src="../assets/images/Icons/Refresh.gif" />Refresh list!</asp:LinkButton>
                    </div>
            </CommandItemTemplate>
                
                <Columns>
                    <telerik:GridBoundColumn DataField="Student_ID" HeaderText="Student_ID" 
                        ReadOnly="True" SortExpression="Student_ID" UniqueName="Student_ID">
                    </telerik:GridBoundColumn>
                    <telerik:GridBoundColumn DataField="Year_of_Joining" DataType="System.Int32" 
                        HeaderText="Year_of_Joining" SortExpression="Year_of_Joining" 
                        UniqueName="Year_of_Joining">
                    </telerik:GridBoundColumn>
                    <telerik:GridBoundColumn DataField="Email" HeaderText="Email" 
                        SortExpression="Email" UniqueName="Email">
                    </telerik:GridBoundColumn>
                    <telerik:GridBoundColumn DataField="First_Name" HeaderText="First_Name" 
                        SortExpression="First_Name" UniqueName="First_Name">
                    </telerik:GridBoundColumn>
                    <telerik:GridBoundColumn DataField="Last_Name" HeaderText="Last_Name" 
                        SortExpression="Last_Name" UniqueName="Last_Name">
                    </telerik:GridBoundColumn>
                  
                 
                    <telerik:GridCheckBoxColumn DataField="Gender" DataType="System.Boolean" 
                        HeaderText="Gender" SortExpression="Gender" UniqueName="Gender">
                    </telerik:GridCheckBoxColumn>
                    <telerik:GridBoundColumn DataField="tenth" DataType="System.Double" 
                        HeaderText="tenth" SortExpression="tenth" UniqueName="tenth">
                    </telerik:GridBoundColumn>
                    <telerik:GridBoundColumn DataField="Inter" DataType="System.Double" 
                        HeaderText="Inter" SortExpression="Inter" UniqueName="Inter">
                    </telerik:GridBoundColumn>
                    <telerik:GridBoundColumn DataField="Overall" DataType="System.Double" 
                        HeaderText="Overall" SortExpression="Overall" UniqueName="Overall">
                    </telerik:GridBoundColumn>
                    <telerik:GridBoundColumn DataField="total_baklogs" DataType="System.Int32" 
                        HeaderText="total_baklogs" SortExpression="total_baklogs" 
                        UniqueName="total_baklogs">
                    </telerik:GridBoundColumn>
                    <telerik:GridBoundColumn DataField="Mobile_Number" HeaderText="Mobile_Number" 
                        SortExpression="Mobile_Number" UniqueName="Mobile_Number">
                    </telerik:GridBoundColumn>
                </Columns>
            </MasterTableView>
            <HeaderContextMenu CssClass="GridContextMenu GridContextMenu_Default" 
                EnableImageSprites="True">
            </HeaderContextMenu>
        </telerik:RadGrid>
        <asp:LinqDataSource ID="LinqDataSource3" runat="server" 
            ContextTypeName="Datbase_ClassesDataContext" EntityTypeName="" 
            TableName="Students" 
            Where="Year == @Year &amp;&amp; Course == @Course &amp;&amp; Department == @Department">
            <WhereParameters>
                <asp:ControlParameter ControlID="DropDownList1" Name="Year" 
                    PropertyName="SelectedValue" Type="Int32" />
                <asp:ControlParameter ControlID="DropDownList2" Name="Course" 
                    PropertyName="SelectedValue" Type="Int32" />
                <asp:ControlParameter ControlID="DropDownList3" Name="Department" 
                    PropertyName="SelectedValue" Type="Int32" />
            </WhereParameters>
        </asp:LinqDataSource>
</div>


    <telerik:RadAjaxLoadingPanel ID="RadAjaxLoadingPanel1" runat="server" Skin="Default">
    </telerik:RadAjaxLoadingPanel>
</asp:Content>

