<%@ Page Title="" Language="C#" MasterPageFile="~/admin.master" AutoEventWireup="true" CodeFile="manageannouncements.aspx.cs" Inherits="admin_manageannouncements" %>

<%@ Register Assembly="Telerik.Web.UI" Namespace="Telerik.Web.UI" TagPrefix="telerik" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" Runat="Server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="sidebartop_placeholder" Runat="Server">
</asp:Content>
<asp:Content ID="Content3" ContentPlaceHolderID="sidebarbottom_placeholder" Runat="Server">
</asp:Content>
<asp:Content ID="Content4" ContentPlaceHolderID="content_heading" Runat="Server">
    Manage Announcements<asp:ScriptManager ID="ScriptManager1" runat="server">
    </asp:ScriptManager>
&nbsp;
</asp:Content>
<asp:Content ID="Content5" ContentPlaceHolderID="content_placeholder" Runat="Server">
    <telerik:RadAjaxPanel ID="RadAjaxPanel1" runat="server" LoadingPanelID="RadAjaxLoadingPanel1">
        <telerik:RadGrid ID="RadGrid2" runat="server" AutoGenerateDeleteColumn="True" 
            DataSourceID="LinqDataSource1" GridLines="None" 
            ondeletecommand="RadGrid2_DeleteCommand" Skin="Windows7" 
            AllowPaging="True" AllowSorting="True">
            <ClientSettings>
                <Scrolling AllowScroll="True" UseStaticHeaders="True" />
            </ClientSettings>
            <MasterTableView AutoGenerateColumns="False" DataKeyNames="ID" 
                DataSourceID="LinqDataSource1">
                <CommandItemSettings ExportToPdfText="Export to Pdf" />
                <RowIndicatorColumn>
                    <HeaderStyle Width="20px" />
                </RowIndicatorColumn>
                <ExpandCollapseColumn>
                    <HeaderStyle Width="20px" />
                </ExpandCollapseColumn>
                <Columns>
                    <telerik:GridBoundColumn DataField="ID" DataType="System.Int32" HeaderText="ID" 
                        ReadOnly="True" SortExpression="ID" UniqueName="ID">
                    </telerik:GridBoundColumn>
                    <telerik:GridBoundColumn DataField="subject" HeaderText="subject" 
                        SortExpression="subject" UniqueName="subject">
                    </telerik:GridBoundColumn>
                    <telerik:GridBoundColumn DataField="to" DataType="System.Int32" HeaderText="to" 
                        SortExpression="to" UniqueName="to">
                    </telerik:GridBoundColumn>
                    <telerik:GridBoundColumn DataField="date" DataType="System.DateTime" 
                        HeaderText="date" SortExpression="date" UniqueName="date">
                    </telerik:GridBoundColumn>
                </Columns>
            </MasterTableView>
            <HeaderContextMenu CssClass="GridContextMenu GridContextMenu_Default" 
                EnableImageSprites="True">
            </HeaderContextMenu>
        </telerik:RadGrid>
        <br />
        <h3 class="h3block_r">
            <asp:Label ID="Label1" runat="server" Text=""></asp:Label>
        </h3>

        <asp:LinqDataSource ID="LinqDataSource1" runat="server" 
            ContextTypeName="Datbase_ClassesDataContext" EntityTypeName="" 
            TableName="announcements" EnableDelete="True" EnableUpdate="True">
        </asp:LinqDataSource>
      </telerik:RadAjaxPanel>
    <telerik:RadAjaxLoadingPanel ID="RadAjaxLoadingPanel1" runat="server" Skin="Default">
    </telerik:RadAjaxLoadingPanel>
</asp:Content>

