<%@ Page Title="" Language="C#" MasterPageFile="~/admin.master" AutoEventWireup="true" CodeFile="Setup_Primary_Data.aspx.cs" Inherits="admin_Setup_Primary_Data" %>

<%@ Register Assembly="Telerik.Web.UI" Namespace="Telerik.Web.UI" TagPrefix="telerik" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" Runat="Server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="sidebartop_placeholder" Runat="Server">
</asp:Content>
<asp:Content ID="Content3" ContentPlaceHolderID="sidebarbottom_placeholder" Runat="Server">
</asp:Content>
<asp:Content ID="Content4" ContentPlaceHolderID="content_heading" Runat="Server">
Setup Primary Data
</asp:Content>
<asp:Content ID="Content5" ContentPlaceHolderID="content_placeholder" Runat="Server">
    <asp:ScriptManager ID="ScriptManager1" runat="server">
    </asp:ScriptManager>
<div style="padding:20px">

<div style="width:400px; float:left; margin-right:10px;margin-bottom:20px;">
<h3>Add Courses</h3>
    <telerik:RadGrid ID="RadGrid1" runat="server" AllowAutomaticDeletes="True" 
        AllowAutomaticInserts="True" AllowAutomaticUpdates="True" 
        AutoGenerateDeleteColumn="True" AutoGenerateEditColumn="True" 
        DataSourceID="LinqDataSource1" GridLines="None" Skin="Windows7" 
        AllowSorting="True" onitemdeleted="RadGrid1_ItemDeleted" 
        oniteminserted="RadGrid1_ItemInserted" onitemupdated="RadGrid1_ItemUpdated" 
        ShowStatusBar="True">
<MasterTableView AutoGenerateColumns="False" CommandItemDisplay="Top" DataKeyNames="ID" 
            DataSourceID="LinqDataSource1" 
            NoMasterRecordsText="No Courses to display.">
<CommandItemSettings ExportToPdfText="Export to Pdf"></CommandItemSettings>

<RowIndicatorColumn>
<HeaderStyle Width="20px"></HeaderStyle>
</RowIndicatorColumn>

<ExpandCollapseColumn>
<HeaderStyle Width="20px"></HeaderStyle>
</ExpandCollapseColumn>
    <Columns>
        <telerik:GridBoundColumn DataField="ID" DataType="System.Int32" HeaderText="ID" 
            ReadOnly="True" SortExpression="ID" UniqueName="ID">
        </telerik:GridBoundColumn>
        <telerik:GridTemplateColumn DataField="Course1" HeaderText="Course" 
            SortExpression="Course1" UniqueName="Course1">
            <EditItemTemplate>
                <asp:TextBox ID="Course1TextBox" runat="server" Text='<%# Bind("Course1") %>'></asp:TextBox>
                
                <span style="color:Red"><asp:RequiredFieldValidator ID="RequiredFieldValidator1" runat="server" ErrorMessage="Required Field" ControlToValidate="Course1TextBox"></asp:RequiredFieldValidator></span>
            </EditItemTemplate>
            <ItemTemplate>
                <asp:Label ID="Course1Label" runat="server" Text='<%# Eval("Course1") %>'></asp:Label>
            </ItemTemplate>
        </telerik:GridTemplateColumn>
    </Columns>
</MasterTableView>

<HeaderContextMenu EnableImageSprites="True" CssClass="GridContextMenu GridContextMenu_Default"></HeaderContextMenu>
    </telerik:RadGrid>
</div>

<div style="width:400px; float:left; margin-right:24px;margin-bottom:20px;">
<h3>Add Departments</h3>
    <telerik:RadGrid ID="RadGrid2" runat="server" AllowAutomaticDeletes="True" 
        AllowAutomaticInserts="True" AllowAutomaticUpdates="True" 
        AutoGenerateDeleteColumn="True" AutoGenerateEditColumn="True" 
        DataSourceID="LinqDataSource2" GridLines="None" Skin="Windows7" 
        onitemdeleted="RadGrid2_ItemDeleted" oniteminserted="RadGrid2_ItemInserted" 
        onitemupdated="RadGrid2_ItemUpdated" ShowStatusBar="True">
<MasterTableView AutoGenerateColumns="False" CommandItemDisplay="Top" DataKeyNames="ID" 
            DataSourceID="LinqDataSource2">
<CommandItemSettings ExportToPdfText="Export to Pdf"></CommandItemSettings>

    <Columns>
        <telerik:GridBoundColumn DataField="ID" DataType="System.Int32" HeaderText="ID" 
            ReadOnly="True" SortExpression="ID" UniqueName="ID">
        </telerik:GridBoundColumn>
        <telerik:GridTemplateColumn DataField="Department1" HeaderText="Department" 
            SortExpression="Department1" UniqueName="Department1">
            <EditItemTemplate>
                <asp:TextBox ID="Department1TextBox" runat="server" 
                    Text='<%# Bind("Department1") %>'></asp:TextBox>
<span style="color:Red">
                <asp:RequiredFieldValidator  ControlToValidate="Department1TextBox" ID="RequiredFieldValidator2" runat="server" ErrorMessage="RequiredField"></asp:RequiredFieldValidator>
                </span>
            </EditItemTemplate>
            <ItemTemplate>
                <asp:Label ID="Department1Label" runat="server" 
                    Text='<%# Eval("Department1") %>'></asp:Label>
            </ItemTemplate>
        </telerik:GridTemplateColumn>
    </Columns>
</MasterTableView>

<HeaderContextMenu EnableImageSprites="True" CssClass="GridContextMenu GridContextMenu_Default"></HeaderContextMenu>
    </telerik:RadGrid>
    <asp:LinqDataSource ID="LinqDataSource2" runat="server" 
        ContextTypeName="Datbase_ClassesDataContext" EnableDelete="True" 
        EnableInsert="True" EnableUpdate="True" EntityTypeName="" 
        TableName="Departments">
    </asp:LinqDataSource>
</div>

<br style="clear:both;"/>
<div style="width:350px; float:left; margin-bottom:20px;">
<h3>Passing Out years</h3>
    <telerik:RadGrid ID="RadGrid3" runat="server" DataSourceID="LinqDataSource3" 
        GridLines="None" Skin="Windows7" AllowAutomaticDeletes="True" 
        AllowAutomaticInserts="True" AllowAutomaticUpdates="True" AllowSorting="True" 
        AutoGenerateDeleteColumn="True" AutoGenerateEditColumn="True" 
        onitemdeleted="RadGrid3_ItemDeleted" oniteminserted="RadGrid3_ItemInserted" 
        onitemupdated="RadGrid3_ItemUpdated" ShowStatusBar="True">
<MasterTableView AutoGenerateColumns="False" DataKeyNames="Year1" 
            DataSourceID="LinqDataSource3" CommandItemDisplay="Top">
<CommandItemSettings ExportToPdfText="Export to Pdf"></CommandItemSettings>

<RowIndicatorColumn>
<HeaderStyle Width="20px"></HeaderStyle>
</RowIndicatorColumn>

<ExpandCollapseColumn>
<HeaderStyle Width="20px"></HeaderStyle>
</ExpandCollapseColumn>
    <Columns>
        <telerik:GridTemplateColumn DataField="Year1" DataType="System.Int32" 
            HeaderText="Passing out Year" SortExpression="Year1" UniqueName="Year1">
            <EditItemTemplate>
                <asp:TextBox ID="Year1TextBox" runat="server" Text='<%# Bind("Year1") %>'></asp:TextBox>
                <span style="color:Red"><asp:RequiredFieldValidator ControlToValidate="Year1TextBox" ID="RequiredFieldValidator3" runat="server" ErrorMessage="Required Field"></asp:RequiredFieldValidator></span>
            </EditItemTemplate>
            <ItemTemplate>
                <asp:Label ID="Year1Label" runat="server" Text='<%# Eval("Year1") %>'></asp:Label>
            </ItemTemplate>
        </telerik:GridTemplateColumn>
    </Columns>
</MasterTableView>

<HeaderContextMenu EnableImageSprites="True" CssClass="GridContextMenu GridContextMenu_Default"></HeaderContextMenu>
    </telerik:RadGrid>

    <asp:LinqDataSource ID="LinqDataSource3" runat="server" 
        ContextTypeName="Datbase_ClassesDataContext" EntityTypeName="" 
        TableName="Years" EnableDelete="True" EnableInsert="True" 
        EnableUpdate="True">
    </asp:LinqDataSource>

</div>

<div style="width:400px; float:left; margin-left:24px;margin-bottom:20px;">
<h3>Add Companies</h3>
    <telerik:RadGrid ID="RadGrid4" runat="server" AllowAutomaticDeletes="True" 
        AllowAutomaticInserts="True" AllowAutomaticUpdates="True" 
        AutoGenerateDeleteColumn="True" AutoGenerateEditColumn="True" 
        DataSourceID="LinqDataSource4" GridLines="None" Skin="Windows7">
<MasterTableView AutoGenerateColumns="False" CommandItemDisplay="Top" DataKeyNames="ID" 
            DataSourceID="LinqDataSource4">
<CommandItemSettings ExportToPdfText="Export to Pdf"></CommandItemSettings>

<RowIndicatorColumn>
<HeaderStyle Width="20px"></HeaderStyle>
</RowIndicatorColumn>

<ExpandCollapseColumn>
<HeaderStyle Width="20px"></HeaderStyle>
</ExpandCollapseColumn>
    <Columns>
        <telerik:GridBoundColumn DataField="ID" DataType="System.Int32" HeaderText="ID" 
            ReadOnly="True" SortExpression="ID" UniqueName="ID">
        </telerik:GridBoundColumn>
        <telerik:GridTemplateColumn DataField="Company_Name" HeaderText="Company_Name" 
            SortExpression="Company_Name" UniqueName="Company_Name">
            <EditItemTemplate>
                <asp:TextBox ID="Company_NameTextBox" runat="server" 
                    Text='<%# Bind("Company_Name") %>'></asp:TextBox>
            </EditItemTemplate>
            <ItemTemplate>
                <asp:Label ID="Company_NameLabel" runat="server" 
                    Text='<%# Eval("Company_Name") %>'></asp:Label>
            </ItemTemplate>
        </telerik:GridTemplateColumn>
        <telerik:GridTemplateColumn DataField="Address" HeaderText="Address" 
            SortExpression="Address" UniqueName="Address">
            <EditItemTemplate>
                <asp:TextBox ID="AddressTextBox" runat="server" Text='<%# Bind("Address") %>' 
                    TextMode="MultiLine"></asp:TextBox>
            </EditItemTemplate>
            <ItemTemplate>
                <asp:Label ID="AddressLabel" runat="server" Text='<%# Eval("Address") %>'></asp:Label>
            </ItemTemplate>
        </telerik:GridTemplateColumn>
        <telerik:GridTemplateColumn DataField="Other" HeaderText="Other" 
            SortExpression="Other" UniqueName="Other">
            <EditItemTemplate>
                <asp:TextBox ID="OtherTextBox" runat="server" Text='<%# Bind("Other") %>' 
                    TextMode="MultiLine"></asp:TextBox>
            </EditItemTemplate>
            <ItemTemplate>
                <asp:Label ID="OtherLabel" runat="server" Text='<%# Eval("Other") %>'></asp:Label>
            </ItemTemplate>
        </telerik:GridTemplateColumn>
    </Columns>
</MasterTableView>

<HeaderContextMenu EnableImageSprites="True" CssClass="GridContextMenu GridContextMenu_Default"></HeaderContextMenu>
    </telerik:RadGrid>

    <asp:LinqDataSource ID="LinqDataSource4" runat="server" 
        ContextTypeName="Datbase_ClassesDataContext" EnableDelete="True" 
        EnableInsert="True" EnableUpdate="True" EntityTypeName="" TableName="Companies">
    </asp:LinqDataSource>

</div>
    <asp:LinqDataSource ID="LinqDataSource1" runat="server" 
        ContextTypeName="Datbase_ClassesDataContext" EnableDelete="True" 
        EnableInsert="True" EnableUpdate="True" EntityTypeName="" TableName="Courses">
    </asp:LinqDataSource>
</div>
</asp:Content>

